server:
  port: 8081
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/SimonSaezCorrea/multitenant
          search-paths: "config-data"